import OpenAI from "openai";
const MODEL="gpt-5.4-mini", IN=.75/1e6, OUT=4.5/1e6;
const BASE="https://raw.githubusercontent.com/oneera1991-cyber/stillwater-ceremony/main/cards/web/";
const CARDS=[
[0,"The Fool","fool.jpg","beginning, openness, leap, possibility, trust, movement into the unknown"],[1,"The Magician","magician.jpg","initiative, ability, action, focus, turning possibility into reality"],[2,"The High Priestess","priestess.jpg","intuition, hidden information, silence, inner knowing, what is not yet revealed"],[3,"The Empress","empress.jpg","growth, care, abundance, attraction, allowing something to develop"],[4,"The Emperor","emperor.jpg","structure, boundaries, stability, control, responsibility"],[5,"The Hierophant","hierophant.jpg","values, guidance, tradition, learning, established ways"],[6,"The Lovers","lovers.jpg","choice, alignment, connection, values, meaningful attraction"],[7,"The Chariot","chariot.jpg","movement, direction, determination, forward momentum"],[8,"Strength","strength.jpg","inner strength, patience, courage, gentle control, emotional steadiness"],[9,"The Hermit","hermit.jpg","withdrawal, reflection, solitude, searching for inner clarity"],[10,"Wheel of Fortune","wheel.jpg","change, cycles, turning point, movement beyond current control"],[11,"Justice","justice.jpg","truth, balance, consequences, clarity, seeing things as they are"],[12,"The Hanged Man","hanged.jpg","pause, waiting, suspension, surrender, new perspective, delayed movement"],[13,"Death","death.jpg","ending, transition, release, transformation, making space for what follows"],[14,"Temperance","temperance.jpg","balance, integration, moderation, gradual movement"],[15,"The Devil","devil.jpg","attachment, fixation, temptation, fear, difficult patterns"],[16,"The Tower","tower.jpg","sudden disruption, revelation, collapse of what is unstable"],[17,"The Star","star.jpg","hope, renewal, openness, guidance, gentle recovery"],[18,"The Moon","moon.jpg","uncertainty, ambiguity, intuition, hidden fears, incomplete information"],[19,"The Sun","sun.jpg","clarity, openness, vitality, confidence, visible truth"],[20,"Judgement","judgement.jpg","awakening, realization, reckoning, response, a call forward"],[21,"The World","world.jpg","completion, integration, closure, arrival, transition to a new cycle"]
].map(([id,name,file,core])=>({id,name,file,core}));
const ANALYZER=`You are the private question-listening intelligence for Stillwater, a Thai tarot experience hosted by Vera. Analyze the human behind the question; never choose a tarot card and never predict the future. Return JSON only: intent, emotional_state, emotional_intensity, situation, core_need, reading_angle, key_signals. Answer in Thai. Infer carefully; do not claim certainty about another person's hidden thoughts. Detect curiosity, hope, anxiety, sadness, confusion, pressure, attachment, fear. Detect waiting, silence, approach, distance, return, beginning, ending, transition, clarity, uncertainty, decision, obstacle, opportunity. emotional_intensity must be low, medium, or high. key_signals: 2-5 short Thai phrases.`;
const READER=`You are Vera, the reading voice inside Stillwater. Write a complete but concise first tarot reading in Thai. Use the user's question analysis as context and the drawn Major Arcana as symbolic anchor. Preserve the card's core meaning. Never use category-template phrases such as ถ้าถามเรื่องความรัก or ถ้าถามเรื่องงาน. Do not reveal internal labels or JSON. Do not guarantee future events or state another person's private thoughts as fact. Pay attention to movement/stillness, approach/distance, contact/silence, clarity/hidden information, beginning/ending/transition, opportunity/obstacle when relevant. If the user is distressed, be gentle and grounded. No medical diagnosis. Make it feel like a direct message from Vera, not a textbook. Aim for 220-360 Thai words.`;
function parse(t){try{return JSON.parse(t)}catch{const m=t.match(/\{[\s\S]*\}/);if(m)return JSON.parse(m[0]);throw Error("AI returned invalid JSON")}}
export default async function handler(req,res){
 if(req.method!=="POST")return res.status(405).json({error:"Method not allowed"});
 try{
  const q=(req.body?.question||"").trim();
  if(q.length<3)return res.status(400).json({error:"กรุณาใส่คำถามก่อน"});
  if(q.length>1200)return res.status(400).json({error:"คำถามยาวเกินไปสำหรับ Prototype นี้"});
  if(!process.env.OPENAI_API_KEY)return res.status(500).json({error:"ยังไม่ได้ตั้งค่า OPENAI_API_KEY ใน Backend"});
  const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY});
  const a=await client.responses.create({model:MODEL,instructions:ANALYZER,input:q,max_output_tokens:500});
  const analysis=parse(a.output_text);
  const card=CARDS[Math.floor(Math.random()*CARDS.length)];
  const r=await client.responses.create({model:MODEL,instructions:READER,input:JSON.stringify({question:q,question_analysis:analysis,drawn_card:{name:card.name,core_meaning:card.core}}),max_output_tokens:900});
  const au=a.usage||{},ru=r.usage||{};
  const u={analysis_input_tokens:au.input_tokens||0,analysis_output_tokens:au.output_tokens||0,reading_input_tokens:ru.input_tokens||0,reading_output_tokens:ru.output_tokens||0};
  u.total_tokens=Object.values(u).reduce((x,y)=>x+y,0); u.estimated_usd=(u.analysis_input_tokens+u.reading_input_tokens)*IN+(u.analysis_output_tokens+u.reading_output_tokens)*OUT;
  return res.status(200).json({analysis,card:{id:card.id,name:card.name,image:BASE+card.file},reading:r.output_text,usage:u});
 }catch(e){console.error(e);return res.status(500).json({error:e?.message||"เกิดข้อผิดพลาดจาก AI"})}
}
